/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitiesIndexRouteImport } from './routes/cities/index'
import { Route as CitiesCompareRouteImport } from './routes/cities/compare'
import { Route as CitiesCityIdRouteImport } from './routes/cities/$cityId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCompareRoute = CitiesCompareRouteImport.update({
  id: '/cities/compare',
  path: '/cities/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdRoute = CitiesCityIdRouteImport.update({
  id: '/cities/$cityId',
  path: '/cities/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/update': typeof UpdateRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/cities/': typeof CitiesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/update': typeof UpdateRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/cities': typeof CitiesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/update': typeof UpdateRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/cities/compare': typeof CitiesCompareRoute
  '/cities/': typeof CitiesIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/update'
    | '/cities/$cityId'
    | '/cities/compare'
    | '/cities/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/update'
    | '/cities/$cityId'
    | '/cities/compare'
    | '/cities'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/update'
    | '/cities/$cityId'
    | '/cities/compare'
    | '/cities/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UpdateRoute: typeof UpdateRoute
  CitiesCityIdRoute: typeof CitiesCityIdRoute
  CitiesCompareRoute: typeof CitiesCompareRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/compare': {
      id: '/cities/compare'
      path: '/cities/compare'
      fullPath: '/cities/compare'
      preLoaderRoute: typeof CitiesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId': {
      id: '/cities/$cityId'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId'
      preLoaderRoute: typeof CitiesCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UpdateRoute: UpdateRoute,
  CitiesCityIdRoute: CitiesCityIdRoute,
  CitiesCompareRoute: CitiesCompareRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
